### ISSUE TITLE
Decrease inference steps lead to crush of output

### ISSUE THREAD

**Issue by Wangchentong** [aqlaboratory/genie2#6]
Hi Yeqing, congratulations on your great work!

I am testing the ability of Genie2 to generate scaffolds with fewer steps. When I reset Genie2's diffusion steps to 100, the output scaffold seems to fail to be a reasonable protein. Have you tested a similar setting? In other words, I am interested in the necessity of 1000 steps during inference, but based on my trials, it seems required. Is such many steps a feature brought by 2d motif input or something else?

![image](https://github.com/aqlaboratory/genie2/assets/91596060/8e1274b1-fbbf-407e-8e6e-b0c67804f6d7)
![image](https://github.com/aqlaboratory/genie2/assets/91596060/4ceda4cd-b4cc-42af-91bf-1eee072278d0)

**Comment by yeqinglin** [comment]
Thank you very much and sorry for the late reply. We tested with some different sampling strategies before with reduced number of inference steps and got back similar results. At this current point, it seems to us that 1000 diffusion steps are necessary during inference. We don’t think this is a result of 2D motif input since this behavior is also observed in unconditional generation, and we suspect this could be related to the use of lower sampling temperature. One of our future direction is to improve the sampling efficiency of Genie 2 and we would investigating further with the possibility of reduced inference steps.

**Comment by Wangchentong** [comment]
Thank you for your comment!
